Added dependencies to tests
- Installed dependencies before testing plugin
- Improved error messages in tests workflow

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -43,6 +43,12 @@ jobs:
           java -jar server.jar || true
           sed -i 's/eula=false/eula=true/g' eula.txt
 
+      # Install dependencies
+      - name: Install plugin dependencies
+        run: |
+          url="https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/artifact/target/ProtocolLib.jar"
+          wget -q "$url" -O ./server/plugins/ProtocolLib.jar
+
       # Install plugin
       - name: Install plugin
         run: |
@@ -57,10 +63,28 @@ jobs:
       - name: Run plugin in server
         working-directory: ./server
         run: |
-          timeout -s SIGINT 1m java -jar server.jar nogui | tee server.log || true
-          if ! grep -Fq '[YamipaPlugin] Loading YamipaPlugin' server.log; then exit 1; fi
-          if ! grep -Fq '[YamipaPlugin] Running on VERBOSE mode' server.log; then exit 1; fi
-          if ! grep -Fq '[YamipaPlugin] Found 5 file(s) in images directory' server.log; then exit 1; fi
-          if ! grep -Fq '[YamipaPlugin] Disabling YamipaPlugin' server.log; then exit 1; fi
-          if grep -Fq 'WARN]:' server.log; then exit 1; fi
-          if grep -Fq 'ERROR]:' server.log; then exit 1; fi
+          timeout -s SIGINT 30s java -jar server.jar nogui | tee server.log || true
+          if ! grep -Fq '[YamipaPlugin] Loading YamipaPlugin' server.log; then
+            echo "Plugin did not load"
+            exit 1
+          fi
+          if ! grep -Fq '[YamipaPlugin] Running on VERBOSE mode' server.log; then
+            echo "Plugin did not enabled verbose mode"
+            exit 1
+          fi
+          if ! grep -Fq '[YamipaPlugin] Found 5 file(s) in images directory' server.log; then
+            echo "Plugin did not read image directory"
+            exit 1
+          fi
+          if ! grep -Fq '[YamipaPlugin] Disabling YamipaPlugin' server.log; then
+            echo "Plugin did not unload"
+            exit 1
+          fi
+          if grep -Fq 'WARN]:' server.log; then
+            echo "Server logged a warning event"
+            exit 1
+          fi
+          if grep -Fq 'ERROR]:' server.log; then
+            echo "Server logged an error event"
+            exit 1
+          fi
